/**
 * agentEnrichment.service.ts — Runs the AI agents at enqueue time to fill in
 * values the client didn't provide, BEFORE the batch is queued.
 *
 * Two enrichments:
 *   1. receiver_name (local var, per recipient) — generated by the first-name
 *      agent when the client sent recipients without names. The UI sends raw
 *      emails (+ optional per-recipient hints); this fills the names. The CLI
 *      already computes names, so we only generate the ones that are missing.
 *   2. product_info (local var) — generated by the product-info agent for ANY
 *      template that declares a `product_info` LOCAL variable (template 4). The
 *      phrase is company-level so it's generated once and attached to every
 *      recipient as a per-recipient local var. Driven purely by the presence of
 *      the local var, so any template using {{product_info}} works.
 *
 * Inputs come from the request body; outputs are normalized local/global
 * variable arrays in the exact shape EmailEnqueueService expects.
 */
import { generateFirstNames, FirstNameInput } from "../agents/first-name.agent";
import { generateProductInfo } from "../agents/product-info.agent";
import logger from "../utils/logger";

export interface RecipientInfo {
  email: string;
  /** Optional free-text hint typed per recipient in the UI / CLI. */
  extraInfo?: string;
}

interface LocalVar {
  key: string;
  description?: string;
  id: string;
  recipient_email?: string;
  value?: string;
}
interface GlobalVar {
  key: string;
  value: string;
  id: string;
}

export interface EnrichInput {
  templateId: string;
  recipients: string[];
  localVariables: LocalVar[];
  globalVariables: GlobalVar[];
  /** Optional per-recipient hints (email -> hint) from the UI/CLI. */
  recipientInfo?: RecipientInfo[];
  /** Optional global instruction typed by the user to steer the agents. */
  extraPrompt?: string;
}

export interface EnrichResult {
  localVariables: LocalVar[];
  globalVariables: GlobalVar[];
}

export class AgentEnrichmentService {
  /**
   * Enrich the incoming variables with agent-generated values. Idempotent and
   * safe: if values already exist (CLI path) they are kept; agents only fill gaps.
   */
  async enrich(input: EnrichInput): Promise<EnrichResult> {
    const {
      recipients,
      recipientInfo = [],
      extraPrompt,
    } = input;

    const localVariables = [...input.localVariables];
    const globalVariables = [...input.globalVariables];

    const hintByEmail = new Map(
      recipientInfo.map((r) => [r.email, r.extraInfo || ""])
    );

    // ── 1. receiver_name per recipient ──────────────────────────────────────
    // A recipient needs generation if there is no receiver_name local var with a
    // non-empty value targeting them (empty string "" is intentional — the API
    // strips empty placeholders — so only undefined/missing triggers the agent).
    const hasNameFor = (email: string): boolean =>
      localVariables.some(
        (v) =>
          v.key === "receiver_name" &&
          (v.recipient_email === email || !v.recipient_email) &&
          v.value !== undefined
      );

    const needNames: FirstNameInput[] = recipients
      .filter((email) => !hasNameFor(email))
      .map((email) => ({ email, extraInfo: hintByEmail.get(email) }));

    if (needNames.length > 0) {
      logger.info("[enrich] generating first names", { count: needNames.length });
      const generated = await generateFirstNames(needNames, extraPrompt);
      generated.forEach((g, idx) => {
        localVariables.push({
          key: "receiver_name",
          description: "Recipient first name",
          id: `agent_local_${idx}`,
          recipient_email: g.email,
          value: g.firstName,
        });
      });
    }

    // ── 2. product_info (LOCAL var, generated by the agent) ─────────────────
    // Driven by the presence of a `product_info` LOCAL variable on the template
    // (template 4). The phrase is company-level (it depends on company_name, a
    // global), so we generate it ONCE and broadcast the same value to every
    // recipient as a per-recipient local var. Attaching it per-recipient (with
    // recipient_email) is required so the renderer's per-recipient branch — the
    // one taken because receiver_name is also per-recipient — actually applies it.
    const productInfoDef = localVariables.find((v) => v.key === "product_info");

    if (productInfoDef) {
      const hasProductInfoFor = (email: string): boolean =>
        localVariables.some(
          (v) =>
            v.key === "product_info" &&
            v.recipient_email === email &&
            v.value !== undefined
        );

      const needProductInfo = recipients.filter(
        (email) => !hasProductInfoFor(email)
      );

      if (needProductInfo.length > 0) {
        const companyName =
          globalVariables.find((v) => v.key === "company_name")?.value ?? "";
        // A value typed on the definition (if any) is treated as a steering hint.
        const hint = productInfoDef.value;

        logger.info("[enrich] generating product_info", {
          companyName,
          recipients: needProductInfo.length,
        });
        const productInfo = await generateProductInfo(
          companyName,
          hint,
          extraPrompt
        );

        if (productInfo) {
          needProductInfo.forEach((email, idx) => {
            localVariables.push({
              key: "product_info",
              description: "Company product/domain phrase",
              id: `agent_product_info_${idx}`,
              recipient_email: email,
              value: productInfo,
            });
          });
        } else {
          logger.warn("[enrich] product_info could not be generated");
        }
      }
    }

    return { localVariables, globalVariables };
  }
}
