/**
 * agentEnrichment.service.ts — Runs the AI agents at enqueue time to fill in
 * values the client didn't provide, BEFORE the batch is queued.
 *
 * Two enrichments:
 *   1. receiver_name (local var, per recipient) — generated by the first-name
 *      agent when the client sent recipients without names. The UI sends raw
 *      emails (+ optional per-recipient hints); this fills the names. The CLI
 *      already computes names, so we only generate the ones that are missing.
 *   2. product_info (global var) — generated by the product-info agent for
 *      template 4 when the client didn't supply it.
 *
 * Inputs come from the request body; outputs are normalized local/global
 * variable arrays in the exact shape EmailEnqueueService expects.
 */
import { generateFirstNames, FirstNameInput } from "../agents/first-name.agent";
import { generateProductInfo } from "../agents/product-info.agent";
import logger from "../utils/logger";

/** Template id for "General Opportunity Exploration" (product_info required). */
const TEMPLATE_4_ID =
  process.env.TEMPLATE_ID_4 || "55ae68ed-caa7-4f2e-adde-98cc31b4df45";

export interface RecipientInfo {
  email: string;
  /** Optional free-text hint typed per recipient in the UI / CLI. */
  extraInfo?: string;
}

interface LocalVar {
  key: string;
  description?: string;
  id: string;
  recipient_email?: string;
  value?: string;
}
interface GlobalVar {
  key: string;
  value: string;
  id: string;
}

export interface EnrichInput {
  templateId: string;
  recipients: string[];
  localVariables: LocalVar[];
  globalVariables: GlobalVar[];
  /** Optional per-recipient hints (email -> hint) from the UI/CLI. */
  recipientInfo?: RecipientInfo[];
  /** Optional global instruction typed by the user to steer the agents. */
  extraPrompt?: string;
}

export interface EnrichResult {
  localVariables: LocalVar[];
  globalVariables: GlobalVar[];
}

export class AgentEnrichmentService {
  /**
   * Enrich the incoming variables with agent-generated values. Idempotent and
   * safe: if values already exist (CLI path) they are kept; agents only fill gaps.
   */
  async enrich(input: EnrichInput): Promise<EnrichResult> {
    const {
      templateId,
      recipients,
      recipientInfo = [],
      extraPrompt,
    } = input;

    const localVariables = [...input.localVariables];
    const globalVariables = [...input.globalVariables];

    const hintByEmail = new Map(
      recipientInfo.map((r) => [r.email, r.extraInfo || ""])
    );

    // ── 1. receiver_name per recipient ──────────────────────────────────────
    // A recipient needs generation if there is no receiver_name local var with a
    // non-empty value targeting them (empty string "" is intentional — the API
    // strips empty placeholders — so only undefined/missing triggers the agent).
    const hasNameFor = (email: string): boolean =>
      localVariables.some(
        (v) =>
          v.key === "receiver_name" &&
          (v.recipient_email === email || !v.recipient_email) &&
          v.value !== undefined
      );

    const needNames: FirstNameInput[] = recipients
      .filter((email) => !hasNameFor(email))
      .map((email) => ({ email, extraInfo: hintByEmail.get(email) }));

    if (needNames.length > 0) {
      logger.info("[enrich] generating first names", { count: needNames.length });
      const generated = await generateFirstNames(needNames, extraPrompt);
      generated.forEach((g, idx) => {
        localVariables.push({
          key: "receiver_name",
          description: "Recipient first name",
          id: `agent_local_${idx}`,
          recipient_email: g.email,
          value: g.firstName,
        });
      });
    }

    // ── 2. product_info for template 4 ──────────────────────────────────────
    const isTemplate4 = templateId === TEMPLATE_4_ID;
    const hasProductInfo = globalVariables.some(
      (v) => v.key === "product_info" && v.value
    );

    if (isTemplate4 && !hasProductInfo) {
      const companyName =
        globalVariables.find((v) => v.key === "company_name")?.value ?? "";
      // A product_info entry may exist with an empty value carrying a hint we
      // pass to the agent; otherwise there is no hint.
      const hint = globalVariables.find((v) => v.key === "product_info")?.value;

      logger.info("[enrich] generating product_info", { companyName });
      const productInfo = await generateProductInfo(
        companyName,
        hint,
        extraPrompt
      );

      if (productInfo) {
        const existing = globalVariables.find((v) => v.key === "product_info");
        if (existing) {
          existing.value = productInfo;
        } else {
          globalVariables.push({
            key: "product_info",
            value: productInfo,
            id: "agent_global_product_info",
          });
        }
      } else {
        logger.warn(
          "[enrich] product_info could not be generated for template 4"
        );
      }
    }

    return { localVariables, globalVariables };
  }
}
